import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// AIWritingEmailAssistant — generated by AppFactoryKit appgen from niche "ai-writing".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum AIWritingEmailAssistantFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "AIWritingEmailAssistant",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "text.bubble",
                          title: "AIWritingEmailAssistant",
                          message: "Draft, rewrite, fix tone of text/emails."),
                    .init(systemImage: "sparkles",
                          title: "Go Pro",
                          message: "Unlimited generations, tones, longer outputs.")
                ],
                presentsPaywallOnFinish: true,
                accent: .blue
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock AIWritingEmailAssistant Pro",
                subheadline: "Unlimited generations, tones, longer outputs.",
                benefits: [
                    .init(systemImage: "infinity", title: "Unlimited generations"),
                    .init(systemImage: "bolt.fill", title: "Tones"),
                    .init(systemImage: "nosign", title: "Longer outputs")
                ],
                productIDs: ["ai-writing_yearly", "ai-writing_weekly"],
                highlightedProductID: "ai-writing_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .blue, heroSystemImage: "text.bubble")
            )
        )
        return AppFactory(config)
    }
}

@main
struct AIWritingEmailAssistantApp: App {
    @StateObject private var factory = AIWritingEmailAssistantFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.blue)
        }
    }
}
